export const ADD_TO_TRACKER = 'ADD_TO_TRACKER'
export const REMOVE_FROM_TRACKER = 'REMOVE_FROM_TRACKER'

export const EDIT_CHARACTER = 'EDIT_CHARACTER'
export const DELETE_CHAR = 'DELETE_CHAR'

export const SAVE_CHAR_TO_CAMPAIGN = 'SAVE_CHAR_TO_CAMPAIGN'

export const SAVE_NPC = 'SAVE_NPC'
export const SAVE_PLAYER = 'SAVE_PLAYER'

export const DELETE_PLAYER = 'DELETE_PLAYER'
export const DELETE_NPC = 'DELETE_NPC'

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN'
export const LOAD_CAMPAIGN = 'LOAD_CAMPAIGN'
export const SAVE_CAMPAIGN = 'SAVE_CAMPAIGN'
export const CLEAR_CAMPAIGN = 'CLEAR_CAMPAIGN'

export const SAVE_ENCOUNTER = 'SAVE_ENCOUNTER'
export const CREATE_ENCOUNTER = 'CREATE_ENCOUNTER'
export const DELETE_ENCOUNTER = 'DELETE_ENCOUNTER'

export const LOAD_ENCOUNTER = 'LOAD_ENCOUNTER'

